version: '3'

tasks:
  install:
    desc: Install bellweaver dependencies with Poetry
    cmds:
      - poetry install --with dev

  test:
    desc: Run all tests with coverage
    cmds:
      - poetry run pytest --cov=bellweaver --cov-report=term-missing

  test:unit:
    desc: Run unit tests only
    cmds:
      - poetry run pytest tests/ -v

  lint:
    desc: Run all linters (ruff, flake8, mypy)
    cmds:
      - poetry run ruff check .
      - poetry run flake8 bellweaver tests
      - poetry run mypy bellweaver

  format:
    desc: Run formatters with auto-fix (ruff, black)
    cmds:
      - poetry run ruff check --fix .
      - poetry run black bellweaver tests

  serve:
    desc: Start Flask API development server
    cmds:
      - poetry run bellweaver api serve

  bootstrap:
    desc: Bootstrap database with sample data for development
    cmds:
      - COMPASS_MODE=mock poetry run bellweaver bootstrap run

  clean:
    desc: Clean build artifacts and caches
    cmds:
      - rm -rf .pytest_cache
      - rm -rf .mypy_cache
      - rm -rf .ruff_cache
      - find . -type d -name "__pycache__" -exec rm -rf {} +
      - find . -type d -name "*.egg-info" -exec rm -rf {} +
